services:
  api:
    build: ./api
    env_file: ./api/.env
    ports: ["8000:8000"]
    depends_on: [redis, db, minio]
    volumes: ["./api:/app"]
    command: ["bash", "run.sh"]
    restart: unless-stopped
    environment:
      API_KEYS: dev_123:tenant_demo
      REDIS_URL: ""

  worker:
    build: ./api
    env_file: ./api/.env
    depends_on: [redis, db, minio]
    volumes: ["./api:/app"]
    command: ["bash", "worker.sh"]
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    ports:
      - "55432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: docdb
      POSTGRES_USER: docuser
      POSTGRES_PASSWORD: docpass
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data

volumes:
  pgdata:
  minio:
